### PR TITLE
vue 2.4X will remove unused node and set the refs to undefined

### PR DESCRIPTION
**Pull request by gloxing**
vue 2.4X will remove unused node and set the refs to undefined

### CODE REVIEW

**Comment by dalphyx** [comment]
@gloxing I can't reproduce this issue in Vue 2.4.4. Can you give a reproduction link?

**Comment by gloxing** [comment]
@dalphyx https://jsfiddle.net/gloxing/Ltjyjjba/
if you click twice, the ref will undefined

**Comment by dalphyx** [comment]
@gloxing I think this may be Vue's bug. I have opened an issue for this and use your link for reproduction :)

**Comment by gloxing** [comment]
@dalphyx thanks

**Comment by dalphyx** [comment]
@gloxing Vue 2.5.0 has fix this bug. So I close this pr:)

**Pull request closed without merging**
